openapi: 3.0.0
info:
  version: v1
  title: Schedule Management
  description: Documentation for the schedule management - Barbershop

servers:
  - description: Localhost
    url: https://localhost:3001/v1

tags: []

paths: {}

components:
  schemas: {}
  responses: {}
